import type { CosmicvortexParams } from "./types";

export const DEFAULT_CONFIG: CosmicvortexParams = {
  particleCount: 3500,
  spiralArms: 4,
  spiralTightness: 1.2,
  rotationSpeed: 0.6,
  trailFade: 0.04,
  innerRadius: 0.08,
  diskRadius: 0.3,
  diskWidth: 0.12,
  particleSize: 1.2,
  glowIntensity: 15,
  warmAccentRatio: 0.15,
  depthIntensity: 0.7,
  bgColor: "#050510",
  diskColor: "#ffffff",
  accentColor: "#ff8844",
};

export interface CosmicvortexPreset {
  id: string;
  label: string;
  params: CosmicvortexParams;
}

export const PRESETS: CosmicvortexPreset[] = [
  {
    id: "deep-space",
    label: "Deep Space",
    params: { ...DEFAULT_CONFIG },
  },
  {
    id: "quasar",
    label: "Quasar",
    params: {
      ...DEFAULT_CONFIG,
      particleCount: 5000,
      spiralArms: 2,
      spiralTightness: 0.8,
      rotationSpeed: 1.2,
      glowIntensity: 30,
      warmAccentRatio: 0.3,
      bgColor: "#080015",
      diskColor: "#aaccff",
      accentColor: "#ff6622",
    },
  },
  {
    id: "red-giant",
    label: "Red Giant",
    params: {
      ...DEFAULT_CONFIG,
      particleCount: 4000,
      spiralArms: 3,
      spiralTightness: 1.5,
      rotationSpeed: 0.4,
      trailFade: 0.03,
      diskWidth: 0.18,
      warmAccentRatio: 0.45,
      bgColor: "#0a0205",
      diskColor: "#ffccaa",
      accentColor: "#ff3322",
    },
  },
  {
    id: "pulsar",
    label: "Pulsar",
    params: {
      ...DEFAULT_CONFIG,
      particleCount: 2500,
      spiralArms: 2,
      spiralTightness: 2.5,
      rotationSpeed: 2.0,
      trailFade: 0.06,
      innerRadius: 0.12,
      diskRadius: 0.25,
      diskWidth: 0.08,
      particleSize: 0.8,
      glowIntensity: 25,
      warmAccentRatio: 0.05,
      bgColor: "#020208",
      diskColor: "#88ccff",
      accentColor: "#ffffff",
    },
  },
  {
    id: "nebula",
    label: "Nebula",
    params: {
      ...DEFAULT_CONFIG,
      particleCount: 4500,
      spiralArms: 6,
      spiralTightness: 0.6,
      rotationSpeed: 0.3,
      trailFade: 0.02,
      diskRadius: 0.4,
      diskWidth: 0.2,
      particleSize: 1.5,
      glowIntensity: 20,
      warmAccentRatio: 0.25,
      bgColor: "#050812",
      diskColor: "#cc99ff",
      accentColor: "#ff66aa",
    },
  },
  {
    id: "singularity",
    label: "Singularity",
    params: {
      ...DEFAULT_CONFIG,
      particleCount: 6000,
      spiralArms: 8,
      spiralTightness: 3.0,
      rotationSpeed: 0.8,
      trailFade: 0.05,
      innerRadius: 0.15,
      diskRadius: 0.22,
      diskWidth: 0.06,
      particleSize: 0.7,
      glowIntensity: 35,
      warmAccentRatio: 0.1,
      bgColor: "#000005",
      diskColor: "#ffffff",
      accentColor: "#ffaa44",
    },
  },
  {
    id: "emerald",
    label: "Emerald",
    params: {
      ...DEFAULT_CONFIG,
      particleCount: 3000,
      spiralArms: 3,
      spiralTightness: 1.0,
      rotationSpeed: 0.5,
      trailFade: 0.035,
      warmAccentRatio: 0.2,
      bgColor: "#020a08",
      diskColor: "#88ffcc",
      accentColor: "#44ff88",
    },
  },
  {
    id: "frozen-void",
    label: "Frozen Void",
    params: {
      ...DEFAULT_CONFIG,
      particleCount: 3000,
      spiralArms: 5,
      spiralTightness: 1.8,
      rotationSpeed: 0.2,
      trailFade: 0.02,
      diskWidth: 0.15,
      particleSize: 1.0,
      glowIntensity: 10,
      warmAccentRatio: 0.0,
      bgColor: "#030810",
      diskColor: "#aaddff",
      accentColor: "#6699cc",
    },
  },
  {
    id: "wide-halo",
    label: "Wide Halo",
    params: {
      ...DEFAULT_CONFIG,
      particleCount: 1600,
      rotationSpeed: 0.1,
      innerRadius: 0.02,
      diskRadius: 0.47,
      diskWidth: 0.3,
      particleSize: 1,
      glowIntensity: 0,
      warmAccentRatio: 0.1,
      depthIntensity: 0.95,
    },
  },
  {
    id: "thin-ring",
    label: "Thin Ring",
    params: {
      ...DEFAULT_CONFIG,
      particleCount: 1400,
      spiralArms: 5,
      spiralTightness: 1.3,
      rotationSpeed: 0.1,
      trailFade: 0.14,
      innerRadius: 0.09,
      diskRadius: 0.39,
      diskWidth: 0.06,
      particleSize: 0.5,
      glowIntensity: 0,
      warmAccentRatio: 0.1,
      depthIntensity: 0.15,
    },
  },
];
