import type { SankeyflowParams, PaletteName } from "./types";

export const PALETTES: Record<PaletteName, string[]> = {
  cyberpunk: ["#00f3ff", "#ff003c", "#bc13fe", "#05d9e8"],
  fire: ["#ff4b00", "#ff9000", "#ffc600", "#ff0000"],
  ocean: ["#00b4d8", "#0077b6", "#48cae4", "#90e0ef"],
  nature: ["#2dc653", "#208b3a", "#d8f3dc", "#74c69d"],
  monochrome: ["#ffffff", "#aaaaaa", "#777777", "#dddddd"],
};

// Shape defaults: circle (no modulation)
const SHAPE_DEFAULTS = {
  petalCount: 0,
  petalDepth: 0,
  aspectRatio: 1,
  spiralTwist: 0,
};

export const DEFAULT_CONFIG: SankeyflowParams = {
  numBranches: 12,
  curvature: 0.8,
  rotationSpeed: 2,
  particleCount: 500,
  baseSpeed: 5,
  flowDirection: "outward",
  palette: "cyberpunk",
  glowIntensity: 15,
  trailFade: 0.15,
  lineWidthMultiplier: 3,
  showParticles: true,
  showCore: true,
  ...SHAPE_DEFAULTS,
};

export interface SankeyflowPreset {
  id: string;
  label: string;
  params: SankeyflowParams;
}

export const PRESETS: SankeyflowPreset[] = [
  {
    id: "cyberpunk",
    label: "Cyberpunk",
    params: { ...DEFAULT_CONFIG },
  },
  {
    id: "turbine",
    label: "Turbine",
    params: {
      ...SHAPE_DEFAULTS,
      numBranches: 16,
      curvature: 1.6,
      rotationSpeed: 3,
      particleCount: 0,
      baseSpeed: 0,
      flowDirection: "outward",
      palette: "monochrome",
      glowIntensity: 0,
      trailFade: 0.08,
      lineWidthMultiplier: 6,
      showParticles: false,
      showCore: true,
    },
  },
  {
    id: "flower",
    label: "Flower",
    params: {
      numBranches: 20,
      curvature: 1.0,
      rotationSpeed: 1,
      particleCount: 0,
      baseSpeed: 0,
      flowDirection: "outward",
      palette: "fire",
      glowIntensity: 0,
      trailFade: 0.06,
      lineWidthMultiplier: 5,
      showParticles: false,
      showCore: true,
      petalCount: 5,
      petalDepth: 0.5,
      aspectRatio: 1,
      spiralTwist: 0,
    },
  },
  {
    id: "galaxy-arm",
    label: "Galaxy",
    params: {
      numBranches: 24,
      curvature: 1.5,
      rotationSpeed: 2,
      particleCount: 600,
      baseSpeed: 3,
      flowDirection: "outward",
      palette: "cyberpunk",
      glowIntensity: 15,
      trailFade: 0.1,
      lineWidthMultiplier: 3,
      showParticles: true,
      showCore: true,
      petalCount: 3,
      petalDepth: 0.3,
      aspectRatio: 1,
      spiralTwist: 1.5,
    },
  },
  {
    id: "supernova",
    label: "Supernova",
    params: {
      ...SHAPE_DEFAULTS,
      numBranches: 24,
      curvature: 1.2,
      rotationSpeed: 1,
      particleCount: 800,
      baseSpeed: 3,
      flowDirection: "outward",
      palette: "fire",
      glowIntensity: 25,
      trailFade: 0.08,
      lineWidthMultiplier: 4,
      showParticles: true,
      showCore: true,
    },
  },
  {
    id: "starfish",
    label: "Starfish",
    params: {
      numBranches: 30,
      curvature: 0.6,
      rotationSpeed: 0.5,
      particleCount: 0,
      baseSpeed: 0,
      flowDirection: "outward",
      palette: "ocean",
      glowIntensity: 0,
      trailFade: 0.06,
      lineWidthMultiplier: 5,
      showParticles: false,
      showCore: false,
      petalCount: 5,
      petalDepth: 0.7,
      aspectRatio: 1,
      spiralTwist: 0.3,
    },
  },
  {
    id: "nebula",
    label: "Nebula",
    params: {
      numBranches: 16,
      curvature: 1.8,
      rotationSpeed: 1,
      particleCount: 500,
      baseSpeed: 2,
      flowDirection: "outward",
      palette: "cyberpunk",
      glowIntensity: 20,
      trailFade: 0.15,
      lineWidthMultiplier: 4,
      showParticles: true,
      showCore: true,
      petalCount: 0,
      petalDepth: 0,
      aspectRatio: 1.8,
      spiralTwist: 0,
    },
  },
  {
    id: "whirlpool",
    label: "Whirlpool",
    params: {
      ...SHAPE_DEFAULTS,
      numBranches: 8,
      curvature: 2.0,
      rotationSpeed: 5,
      particleCount: 600,
      baseSpeed: 4,
      flowDirection: "inward",
      palette: "ocean",
      glowIntensity: 20,
      trailFade: 0.1,
      lineWidthMultiplier: 3,
      showParticles: true,
      showCore: true,
      spiralTwist: 1.0,
    },
  },
  {
    id: "spiral-rose",
    label: "Rose",
    params: {
      numBranches: 24,
      curvature: 1.2,
      rotationSpeed: 1.5,
      particleCount: 0,
      baseSpeed: 0,
      flowDirection: "outward",
      palette: "fire",
      glowIntensity: 0,
      trailFade: 0.05,
      lineWidthMultiplier: 4,
      showParticles: false,
      showCore: true,
      petalCount: 8,
      petalDepth: 0.4,
      aspectRatio: 1,
      spiralTwist: 2.0,
    },
  },
  {
    id: "singularity",
    label: "Singularity",
    params: {
      ...SHAPE_DEFAULTS,
      numBranches: 32,
      curvature: 1.8,
      rotationSpeed: 3,
      particleCount: 1000,
      baseSpeed: 8,
      flowDirection: "inward",
      palette: "monochrome",
      glowIntensity: 10,
      trailFade: 0.2,
      lineWidthMultiplier: 2,
      showParticles: true,
      showCore: true,
    },
  },
  {
    id: "solar-storm",
    label: "Solar Storm",
    params: {
      ...SHAPE_DEFAULTS,
      numBranches: 6,
      curvature: 2.5,
      rotationSpeed: 8,
      particleCount: 700,
      baseSpeed: 12,
      flowDirection: "outward",
      palette: "fire",
      glowIntensity: 35,
      trailFade: 0.05,
      lineWidthMultiplier: 2,
      showParticles: true,
      showCore: true,
    },
  },
  {
    id: "deep-sea",
    label: "Deep Sea",
    params: {
      ...SHAPE_DEFAULTS,
      numBranches: 20,
      curvature: 1.0,
      rotationSpeed: -1,
      particleCount: 500,
      baseSpeed: 2,
      flowDirection: "outward",
      palette: "ocean",
      glowIntensity: 18,
      trailFade: 0.25,
      lineWidthMultiplier: 4,
      showParticles: true,
      showCore: true,
    },
  },
];
