import type { RadialflowParams } from "./types";

export const DEFAULT_CONFIG: RadialflowParams = {
  nodeCount: 8,
  particleCount: 200,
  speed: 5,
  particleSize: 2,
  trailLength: 0.1,
  curvature: 0.5,
  direction: "outward",
  colorMode: "gradient",
  primaryColor: "#10b981",
  secondaryColor: "#3b82f6",
  glowIntensity: 15,
  rotationSpeed: 1,
};

export interface RadialflowPreset {
  id: string;
  label: string;
  emoji: string;
  params: RadialflowParams;
}

export const PRESETS: RadialflowPreset[] = [
  {
    id: "emerald-stream",
    label: "Emerald",
    emoji: "🌿",
    params: { ...DEFAULT_CONFIG },
  },
  {
    id: "solar-flare",
    label: "Solar Flare",
    emoji: "☀️",
    params: {
      nodeCount: 12,
      particleCount: 500,
      speed: 8,
      particleSize: 3,
      trailLength: 0.15,
      curvature: 0.8,
      direction: "outward",
      colorMode: "gradient",
      primaryColor: "#ff6600",
      secondaryColor: "#ffcc00",
      glowIntensity: 30,
      rotationSpeed: 0.5,
    },
  },
  {
    id: "black-hole",
    label: "Black Hole",
    emoji: "🕳️",
    params: {
      nodeCount: 16,
      particleCount: 600,
      speed: 3,
      particleSize: 1.5,
      trailLength: 0.25,
      curvature: 1.8,
      direction: "inward",
      colorMode: "gradient",
      primaryColor: "#8b5cf6",
      secondaryColor: "#06b6d4",
      glowIntensity: 20,
      rotationSpeed: 2,
    },
  },
  {
    id: "aurora",
    label: "Aurora",
    emoji: "🌌",
    params: {
      nodeCount: 6,
      particleCount: 400,
      speed: 3,
      particleSize: 2.5,
      trailLength: 0.3,
      curvature: -0.5,
      direction: "outward",
      colorMode: "gradient",
      primaryColor: "#00ff88",
      secondaryColor: "#ff00aa",
      glowIntensity: 25,
      rotationSpeed: 0.3,
    },
  },
  {
    id: "neon-spinner",
    label: "Neon Spin",
    emoji: "💫",
    params: {
      nodeCount: 4,
      particleCount: 300,
      speed: 10,
      particleSize: 2,
      trailLength: 0.08,
      curvature: 1.2,
      direction: "outward",
      colorMode: "rainbow",
      primaryColor: "#ff0066",
      secondaryColor: "#00ffcc",
      glowIntensity: 35,
      rotationSpeed: 5,
    },
  },
  {
    id: "galaxy",
    label: "Galaxy",
    emoji: "🌀",
    params: {
      nodeCount: 24,
      particleCount: 800,
      speed: 2,
      particleSize: 1,
      trailLength: 0.35,
      curvature: -1.5,
      direction: "outward",
      colorMode: "rainbow",
      primaryColor: "#ffffff",
      secondaryColor: "#aaaaff",
      glowIntensity: 10,
      rotationSpeed: 0.8,
    },
  },
  {
    id: "heartbeat",
    label: "Heartbeat",
    emoji: "💓",
    params: {
      nodeCount: 2,
      particleCount: 150,
      speed: 15,
      particleSize: 4,
      trailLength: 0.05,
      curvature: 0.3,
      direction: "outward",
      colorMode: "monochrome",
      primaryColor: "#ff1744",
      secondaryColor: "#ff1744",
      glowIntensity: 40,
      rotationSpeed: 0,
    },
  },
  {
    id: "ice-crystal",
    label: "Ice Crystal",
    emoji: "❄️",
    params: {
      nodeCount: 6,
      particleCount: 350,
      speed: 2,
      particleSize: 1.5,
      trailLength: 0.4,
      curvature: 0,
      direction: "outward",
      colorMode: "gradient",
      primaryColor: "#e0f7fa",
      secondaryColor: "#0288d1",
      glowIntensity: 18,
      rotationSpeed: -0.5,
    },
  },
  {
    id: "firewheel",
    label: "Firewheel",
    emoji: "🔥",
    params: {
      nodeCount: 8,
      particleCount: 500,
      speed: 12,
      particleSize: 2.5,
      trailLength: 0.12,
      curvature: 2.0,
      direction: "outward",
      colorMode: "gradient",
      primaryColor: "#ff3300",
      secondaryColor: "#ffaa00",
      glowIntensity: 45,
      rotationSpeed: 8,
    },
  },
  {
    id: "rainbow-vortex",
    label: "Vortex",
    emoji: "🌈",
    params: {
      nodeCount: 24,
      particleCount: 220,
      speed: 6,
      particleSize: 4.5,
      trailLength: 0.3,
      curvature: -1.9,
      direction: "inward",
      colorMode: "rainbow",
      primaryColor: "#22c55e",
      secondaryColor: "#3b5bdb",
      glowIntensity: 35,
      rotationSpeed: 7.5,
    },
  },
  {
    id: "zen-garden",
    label: "Zen",
    emoji: "🪷",
    params: {
      nodeCount: 32,
      particleCount: 1000,
      speed: 1,
      particleSize: 0.5,
      trailLength: 0.5,
      curvature: 0.2,
      direction: "inward",
      colorMode: "monochrome",
      primaryColor: "#c8b89a",
      secondaryColor: "#c8b89a",
      glowIntensity: 5,
      rotationSpeed: 0.2,
    },
  },
];
