import type { LiquidtransParams } from "./types";

export const DEFAULT_CONFIG: LiquidtransParams = {
  speed: 0.4,
  scale: 2.0,
  swirl: 3.0,
  turbulence: 1.0,
  edgeSoftness: 0.3,
  color1: "#3344ff",
  color2: "#ff66bb",
  color3: "#ffdd00",
  vignette: 0.0,
  grain: 0.0,
  paused: false,
  mouseForce: 0.0,
  mouseRadius: 0.3,
  symmetry: 1,
  hueDrift: 0.0,
  distortion: "swirl",
  texture: "flat",
};

export interface LiquidtransPreset {
  id: string;
  label: string;
  params: LiquidtransParams;
}

export const PRESETS: LiquidtransPreset[] = [
  {
    id: "oil-paint",
    label: "Oil Paint",
    params: {
      speed: 0.4,
      scale: 2.0,
      swirl: 3.0,
      turbulence: 1.0,
      edgeSoftness: 0.3,
      color1: "#3344ff",
      color2: "#ff66bb",
      color3: "#ffdd00",
      vignette: 0.0,
      grain: 0.0,
      paused: false,
      mouseForce: 0.0,
      mouseRadius: 0.3,
      symmetry: 1,
      hueDrift: 0.0,
      distortion: "swirl",
      texture: "oil",
    },
  },
  {
    id: "lava-flow",
    label: "Lava Flow",
    params: {
      speed: 0.2,
      scale: 1.8,
      swirl: 4.0,
      turbulence: 1.4,
      edgeSoftness: 0.15,
      color1: "#1a0500",
      color2: "#cc2200",
      color3: "#ff8800",
      vignette: 0.0,
      grain: 0.0,
      paused: false,
      mouseForce: 0.0,
      mouseRadius: 0.3,
      symmetry: 1,
      hueDrift: 0.0,
      distortion: "swirl",
      texture: "flat",
    },
  },
  {
    id: "ocean-current",
    label: "Ocean",
    params: {
      speed: 0.25,
      scale: 2.5,
      swirl: 3.5,
      turbulence: 0.8,
      edgeSoftness: 0.45,
      color1: "#0a1628",
      color2: "#1a6888",
      color3: "#88ddee",
      vignette: 0.0,
      grain: 0.0,
      paused: false,
      mouseForce: 0.0,
      mouseRadius: 0.3,
      symmetry: 1,
      hueDrift: 0.0,
      distortion: "swirl",
      texture: "silk",
    },
  },
  {
    id: "neon-ink",
    label: "Neon Ink",
    params: {
      speed: 0.6,
      scale: 1.5,
      swirl: 5.0,
      turbulence: 1.2,
      edgeSoftness: 0.2,
      color1: "#00ffaa",
      color2: "#ff00aa",
      color3: "#00ccff",
      vignette: 0.0,
      grain: 0.0,
      paused: false,
      mouseForce: 0.0,
      mouseRadius: 0.3,
      symmetry: 1,
      hueDrift: 0.0,
      distortion: "swirl",
      texture: "metal",
    },
  },
  {
    id: "sunset-marble",
    label: "Sunset",
    params: {
      speed: 0.3,
      scale: 2.2,
      swirl: 2.5,
      turbulence: 0.9,
      edgeSoftness: 0.4,
      color1: "#6622aa",
      color2: "#ee5533",
      color3: "#ffcc22",
      vignette: 0.0,
      grain: 0.0,
      paused: false,
      mouseForce: 0.0,
      mouseRadius: 0.3,
      symmetry: 1,
      hueDrift: 0.0,
      distortion: "swirl",
      texture: "flat",
    },
  },
  {
    id: "midnight-aurora",
    label: "Aurora",
    params: {
      speed: 0.15,
      scale: 3.0,
      swirl: 2.0,
      turbulence: 0.7,
      edgeSoftness: 0.55,
      color1: "#0a0a2e",
      color2: "#22aa66",
      color3: "#6644cc",
      vignette: 0.0,
      grain: 0.0,
      paused: false,
      mouseForce: 0.0,
      mouseRadius: 0.3,
      symmetry: 1,
      hueDrift: 0.0,
      distortion: "swirl",
      texture: "silk",
    },
  },
  {
    id: "candy-melt",
    label: "Candy",
    params: {
      speed: 0.35,
      scale: 2.0,
      swirl: 3.5,
      turbulence: 0.6,
      edgeSoftness: 0.5,
      color1: "#aaddff",
      color2: "#ffaacc",
      color3: "#ffffaa",
      vignette: 0.0,
      grain: 0.0,
      paused: false,
      mouseForce: 0.0,
      mouseRadius: 0.3,
      symmetry: 1,
      hueDrift: 0.0,
      distortion: "swirl",
      texture: "watercolor",
    },
  },
  {
    id: "monochrome",
    label: "Mono",
    params: {
      speed: 0.3,
      scale: 2.0,
      swirl: 3.0,
      turbulence: 1.3,
      edgeSoftness: 0.1,
      color1: "#000000",
      color2: "#555555",
      color3: "#ffffff",
      vignette: 0.0,
      grain: 0.0,
      paused: false,
      mouseForce: 0.0,
      mouseRadius: 0.3,
      symmetry: 1,
      hueDrift: 0.0,
      distortion: "swirl",
      texture: "flat",
    },
  },
  // --- New presets using new features ---
  {
    id: "mandala",
    label: "Mandala",
    params: {
      speed: 0.15,
      scale: 2.5,
      swirl: 2.5,
      turbulence: 0.8,
      edgeSoftness: 0.35,
      color1: "#0a1040",
      color2: "#1a3088",
      color3: "#ccaa33",
      vignette: 0.7,
      grain: 0.0,
      paused: false,
      mouseForce: 0.0,
      mouseRadius: 0.3,
      symmetry: 6,
      hueDrift: 0.0,
      distortion: "swirl",
      texture: "silk",
    },
  },
  {
    id: "inkblot",
    label: "Inkblot",
    params: {
      speed: 0.25,
      scale: 2.0,
      swirl: 3.0,
      turbulence: 1.5,
      edgeSoftness: 0.1,
      color1: "#0a0a0a",
      color2: "#444444",
      color3: "#cccccc",
      vignette: 0.4,
      grain: 0.2,
      paused: false,
      mouseForce: 0.0,
      mouseRadius: 0.3,
      symmetry: 2,
      hueDrift: 0.0,
      distortion: "turbulent",
      texture: "watercolor",
    },
  },
  {
    id: "interactive",
    label: "Interactive",
    params: {
      speed: 0.4,
      scale: 2.0,
      swirl: 3.5,
      turbulence: 1.0,
      edgeSoftness: 0.3,
      color1: "#ff00ff",
      color2: "#00ffff",
      color3: "#ffff00",
      vignette: 0.0,
      grain: 0.0,
      paused: false,
      mouseForce: 2.0,
      mouseRadius: 0.4,
      symmetry: 1,
      hueDrift: 0.3,
      distortion: "swirl",
      texture: "metal",
    },
  },
  {
    id: "dreamscape",
    label: "Dreamscape",
    params: {
      speed: 0.2,
      scale: 2.8,
      swirl: 2.0,
      turbulence: 0.7,
      edgeSoftness: 0.5,
      color1: "#eeb8dd",
      color2: "#aaccee",
      color3: "#ddeebb",
      vignette: 0.3,
      grain: 0.05,
      paused: false,
      mouseForce: 0.0,
      mouseRadius: 0.3,
      symmetry: 4,
      hueDrift: 0.15,
      distortion: "radial",
      texture: "silk",
    },
  },
];
